export const productData = [
  {
    id: 1,
    title: "Short",
    src: "img/short.png",
    price: 100,
    category: "bottoms",
  },
  {
    id: 2,
    title: "Tshirt",
    src: "img/tshirt.png",
    price: 150,
    category: "tops",
  },
  {
    id: 3,
    title: "Spor Shoes",
    src: "img/sporayakkabı.png",
    price: 120,
    category: "footwear",
  },
  {
    id: 4,
    title: "Hat",
    src: "img/hat.png",
    price: 50,
    category: "accessories",
  },
  {
    id: 5,
    title: "Straw hat",
    src: "img/hasırşapka.png",
    price: 60,
    category: "accessories",
  },
  {
    id: 6,
    title: "Sunglasses",
    src: "img/güneşgözlüğü.png",
    price: 30,
    category: "accessories",
  },
  {
    id: 7,
    title: "Jacket",
    src: "img/ceket.png",
    price: 500,
    category: "tops",
  },
  {
    id: 8,
    title: "Coat",
    src: "img/mont.png",
    price: 1000,
    category: "tops",
  },
  {
    id: 9,
    title: "Sandal Shoes",
    src: "img/sandalayakkabı.png",
    price: 100,
    category: "footwear",
  },
  {
    id: 10,
    title: "Jumper",
    src: "img/kazak.png",
    price: 80,
    category: "tops",
  },
  {
    id: 11,
    title: "Denim Tracksuit",
    src: "img/koteşofman.png",
    price: 170,
    category: "bottoms",
  },
  {
    id: 12,
    title: "Jeans",
    src: "img/kotpantolon.png",
    price: 250,
    category: "bottoms",
  },
  {
    id: 13,
    title: "Leather shoes",
    src: "img/deriayakkabı.png",
    price: 350,
    category: "footwear",
  },
  {
    id: 14,
    title: "Tracksuit",
    src: "img/eşofman.png",
    price: 150,
    category: "bottoms",
  },
];
